/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import com.mycompany.listacompras.Item;
import com.mycompany.listacompras.Lista;
import com.mycompany.listacompras.atalho.Atalho;
import dao.ItemDAO;
import dao.ListaDAO;
import dao.ListaItemDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cauev
 */
public class TelaLista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLista.class.getName());

    /**
     * Creates new form TelaLista
     */
    private Lista lista;
    private DefaultTableModel model;

    public TelaLista(Lista lista) {
        initComponents();

        tabela.setDefaultEditor(Object.class, null);

        this.lista = lista;

        ListaItemDAO listaItemDAO = new ListaItemDAO();

        this.lista.getItens().addAll(
                listaItemDAO.listarItensDaLista(lista.getId())
        );

        model = (DefaultTableModel) tabela.getModel();

        carregarItens();
    }

private void carregarItens() {

    model.setRowCount(0);

    lista.getItens().clear();

    ListaItemDAO dao = new ListaItemDAO();

    lista.getItens().addAll(
        dao.listarItensDaLista(lista.getId())
    );

    for (Item i : lista.getItens()) {

        model.addRow(new Object[]{
            i.getNome(),
            i.getMarcaFornecedor(),
            i.getQuantidade(),
            i.isComprado() ? "Comprado" : "Pendente"
        });
    }
}



private void adicionarItemLista() {

    ItemDAO itemDAO = new ItemDAO();

    ArrayList<Item> itensBanco = itemDAO.listar();

    if (itensBanco.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Nenhum item cadastrado!"
        );

        return;
    }

    String[] nomesItens = new String[itensBanco.size()];

    for (int i = 0; i < nomesItens.length; i++) {

        nomesItens[i] =
                itensBanco.get(i).getNome();
    }

    String escolhido = (String) JOptionPane.showInputDialog(
            this,
            "Escolha um item:",
            "Adicionar Item",
            JOptionPane.PLAIN_MESSAGE,
            null,
            nomesItens,
            nomesItens[0]
    );

    if (escolhido != null) {

        for (Item item : itensBanco) {

            if (item.getNome().equals(escolhido)) {

                String qtdTexto =
                        JOptionPane.showInputDialog(
                                this,
                                "Digite a quantidade:"
                        );

                try {

                    int qtd = Integer.parseInt(qtdTexto);

                    Item copia = new Item(
                            item.getId(),
                            item.getNome(),
                            qtd,
                            item.getMarcaFornecedor()
                    );

                    lista.adicionarItem(copia);

                    ListaItemDAO listaItemDAO =
                            new ListaItemDAO();

                    listaItemDAO.salvar(
                            lista.getId(),
                            item.getId(),
                            qtd
                    );

                } catch (NumberFormatException e) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Digite um número válido!"
                    );
                }

                break;
            }
        }

        carregarItens();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbSair = new javax.swing.JButton();
        jbTelaInicio = new javax.swing.JButton();
        jbTelaListas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jbAdicionarItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jbSair.setBackground(new java.awt.Color(153, 51, 255));
        jbSair.setText("SAIR");
        jbSair.addActionListener(this::jbSairActionPerformed);

        jbTelaInicio.setBackground(new java.awt.Color(0, 0, 102));
        jbTelaInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbTelaInicio.setText("Início");
        jbTelaInicio.addActionListener(this::jbTelaInicioActionPerformed);

        jbTelaListas.setBackground(new java.awt.Color(0, 0, 102));
        jbTelaListas.setForeground(new java.awt.Color(255, 255, 255));
        jbTelaListas.setText("Listas");
        jbTelaListas.addActionListener(this::jbTelaListasActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbTelaListas)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jbTelaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTelaListas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jbSair)
                .addContainerGap())
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Marca", "Qtd", "Status"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jbAdicionarItem.setText("Add Item");
        jbAdicionarItem.addActionListener(this::jbAdicionarItemActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAdicionarItem)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAdicionarItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbTelaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTelaInicioActionPerformed
        new Mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbTelaInicioActionPerformed

    private void jbTelaListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTelaListasActionPerformed
        new Listas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbTelaListasActionPerformed

    private void jbAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarItemActionPerformed
        adicionarItemLista();
    }//GEN-LAST:event_jbAdicionarItemActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    if (evt.getClickCount() == 2) {

        int linha = tabela.getSelectedRow();

        if (linha != -1) {

            Item item = lista.getItens().get(linha);

            boolean novoStatus = !item.isComprado();

            item.setComprado(novoStatus);

            ListaItemDAO dao = new ListaItemDAO();

            dao.atualizarStatus(
                lista.getId(),
                item.getId(),
                novoStatus
            );

            carregarItens();
        }
    }
    }//GEN-LAST:event_tabelaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionarItem;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbTelaInicio;
    private javax.swing.JButton jbTelaListas;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
